"""Load specialist/nuclei inputs shell.

Shell mixin; hard max 2000 LOC.
"""

from __future__ import annotations

import asyncio
import json
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union
from datetime import datetime
from loguru import logger

from bugtrace.core.config import settings
from bugtrace.core.ui import dashboard
from bugtrace.core.llm_client import llm_client

from bugtrace.agents.base import BaseAgent
from bugtrace.core.database import get_db_manager
from bugtrace.core.event_bus import EventType, event_bus
from bugtrace.core.validation_status import ValidationStatus
from bugtrace.utils.json_parser import safe_json_loads, extract_json_list
from bugtrace.utils.logger import get_logger
from bugtrace.reporting.standards import (
    get_cwe_for_vuln, get_remediation_for_vuln, get_reference_cve,
    normalize_severity, format_cve,
)
from bugtrace.reporting.poc_format import (
    build_query_url, curl_form_field, curl_get, curl_raw_body, curl_header,
    evidence_pairs, md_code_block, md_evidence_block, md_injection_point,
    md_labeled_block, md_document_with_values, md_step_with_block,
    md_step_with_value, plain_evidence_block, shell_word,
    template_expression_result, truncate_marked,
)
import hashlib
import math
import os
import shutil
import time

class ReportingLoadMixin:
    async def run_loop(self):
        """Not used - call generate_all_deliverables() directly."""
        pass

    def _load_specialist_results(self) -> List[Dict]:
        """
        Load findings from specialist report files.

        v3.2: Reads from MULTIPLE sources (in priority order):
        1. specialists/*_report.json - REAL exploitation results from specialist agents
        2. specialists/results/*_results.json - Generated by team.py from wet/ files

        Returns:
            List of findings from all specialist files
        """
        from bugtrace.core.payload_format import decode_finding_payloads

        all_findings = []
        specialists_dir = self.output_dir / "specialists"

        if not specialists_dir.exists():
            logger.debug(f"[{self.name}] specialists/ directory not found")
            return []

        # Priority 1: Load from specialist *_report.json files (REAL exploitation results)
        # These are written by specialist agents (xss_agent, sqli_agent, etc.) after exploitation
        for report_file in specialists_dir.glob("*_report.json"):
            findings = self._load_findings_from_report_file(report_file, decode_finding_payloads)
            all_findings.extend(findings)

        # Priority 2: Load from results/*_results.json (team.py generated from wet/)
        results_dir = specialists_dir / "results"
        if results_dir.exists():
            for result_file in results_dir.glob("*_results.json"):
                findings = self._load_findings_from_results_file(result_file, decode_finding_payloads)
                all_findings.extend(findings)

        # Priority 3: Load from wet/*.json (raw findings from ThinkingAgent)
        wet_dir = specialists_dir / "wet"
        if wet_dir.exists() and not all_findings:
            for wet_file in wet_dir.glob("*.json"):
                findings = self._load_findings_from_wet_file(wet_file, decode_finding_payloads)
                all_findings.extend(findings)
            logger.info(f"[{self.name}] Loaded {len(all_findings)} findings from wet/ (fallback)")

        # Deduplicate by exact (url, parameter, payload) match
        all_findings = self._deduplicate_exact(all_findings)

        logger.info(f"[{self.name}] Loaded {len(all_findings)} total findings from specialist files")
        return all_findings

    def _parse_nuclei_tech_for_report(self) -> Dict[str, Any]:
        """Parse raw Nuclei findings into a structured tech summary for the report.

        Extracts actual version numbers, EOL status, and product names from
        raw_tech_findings and raw_vuln_findings instead of showing template names.

        Returns:
            Dict with keys: technologies (list of dicts), waf_details (list), summary (str)
        """
        if not self.tech_profile:
            return {"technologies": [], "waf_details": [], "summary": ""}

        raw_findings = (
            self.tech_profile.get("raw_tech_findings", [])
            + self.tech_profile.get("raw_vuln_findings", [])
        )

        # Known product display names (avoid "Php", show "PHP" etc.)
        _DISPLAY_NAMES = {
            "php": "PHP", "asp": "ASP.NET", "iis": "IIS", "aws": "AWS",
            "gcp": "GCP", "cdn": "CDN", "jquery": "jQuery", "angularjs": "AngularJS",
            "vuejs": "Vue.js", "nodejs": "Node.js", "reactjs": "React",
        }

        def _display_name(raw: str) -> str:
            if not raw:
                return "Unknown"
            return _DISPLAY_NAMES.get(raw.lower(), raw.capitalize())

        # Merge findings by product/technology, keeping best version info
        tech_map: Dict[str, Dict] = {}  # key = normalized product name (lowercase)
        waf_details_set: set = set()
        waf_details = []

        for finding in raw_findings:
            template_id = finding.get("template-id", "")
            info = finding.get("info", {})
            name = info.get("name", "")
            metadata = info.get("metadata", {})
            extracted = finding.get("extracted-results", [])
            matcher_name = finding.get("matcher-name", "")

            # WAF detection → only include if verified by NucleiAgent FP filter
            if template_id == "waf-detect":
                if not self.tech_profile.get("waf"):
                    continue  # All WAF detections were filtered as FP
                waf_type = matcher_name.replace("generic", "").strip() if matcher_name else "Unknown"
                if waf_type and waf_type.lower() not in waf_details_set:
                    waf_details_set.add(waf_type.lower())
                    waf_details.append(_display_name(waf_type))
                continue

            # Wappalyzer tech-detect → use matcher-name as product
            if template_id == "tech-detect":
                product = _display_name(matcher_name) if matcher_name else ""
                if not product:
                    continue
                key = matcher_name.lower() if matcher_name else ""
                if key not in tech_map:
                    tech_map[key] = {
                        "name": product,
                        "version": None,
                        "eol": False,
                        "category": "Technology",
                    }
                continue

            # Skip security misconfig findings — these are NOT technologies
            _MISCONFIG_PREFIXES = (
                "http-missing-", "missing-", "cookies-without-",
                "cookies-", "security-headers-", "cors-", "cluster-",
            )
            if any(template_id.startswith(p) for p in _MISCONFIG_PREFIXES):
                continue

            # Version/EOL detections → extract product + version
            raw_product = metadata.get("product", "")
            product = _display_name(raw_product) if raw_product else ""
            if not product:
                # Infer from template-id: e.g. "nginx-version" → "Nginx"
                raw_product = template_id.split("-")[0] if template_id else ""
                product = _display_name(raw_product) if raw_product else ""
            if not product:
                continue

            key = product.lower()
            is_eol = "eol" in template_id

            # Extract version from results
            version = None
            if extracted:
                raw_ver = extracted[0]
                # Clean: "nginx/1.19.0" → "1.19.0"
                if "/" in raw_ver:
                    version = raw_ver.split("/", 1)[1]
                else:
                    version = raw_ver

            # Determine category
            category = "Technology"
            if any(x in key for x in ["nginx", "apache", "iis", "tomcat", "lighttpd"]):
                category = "Web Server"
            elif any(x in key for x in ["php", "python", "node", "ruby", "java", "asp", "perl"]):
                category = "Language / Runtime"
            elif any(x in key for x in ["angular", "react", "vue", "jquery", "bootstrap"]):
                category = "Framework"
            elif any(x in key for x in ["wordpress", "drupal", "joomla", "magento"]):
                category = "CMS"
            elif any(x in key for x in ["aws", "azure", "gcp", "cloudfront"]):
                category = "Infrastructure"
            elif any(x in key for x in ["cloudflare", "akamai", "fastly"]):
                category = "CDN"

            if key in tech_map:
                # Merge: prefer version, accumulate EOL
                if version and not tech_map[key]["version"]:
                    tech_map[key]["version"] = version
                if is_eol:
                    tech_map[key]["eol"] = True
                if category != "Technology":
                    tech_map[key]["category"] = category
            else:
                tech_map[key] = {
                    "name": product,
                    "version": version,
                    "eol": is_eol,
                    "category": category,
                }

        technologies = sorted(tech_map.values(), key=lambda t: t["name"])
        return {
            "technologies": technologies,
            "waf_details": waf_details,
            "summary": ", ".join(
                f"{t['name']} {t['version'] or ''}" .strip()
                for t in technologies if t["version"]
            ),
        }

    def _nuclei_load_file(self, path: Path) -> Optional[Dict]:
        """Load and parse tech_profile.json file."""
        try:
            with open(path, "r") as f:
                return json.load(f)
        except Exception as e:
            logger.warning(f"[{self.name}] Failed to load tech_profile.json: {e}")
            return None

    @staticmethod
    def _nuclei_source_value(finding: Dict, *keys: str) -> Any:
        """Read standard Nuclei JSON aliases without losing template identity."""
        for key in keys:
            value = finding.get(key)
            if value not in (None, "", [], {}):
                return value
        return ""

    def _nuclei_extract_tech_stack(self, tech_profile: Dict) -> Dict:
        """Extract full tech stack info from tech profile."""
        return {
            "frameworks": tech_profile.get("frameworks", []),
            "languages": tech_profile.get("languages", []),
            "servers": tech_profile.get("servers", []),
            "waf": tech_profile.get("waf", []),
            "infrastructure": tech_profile.get("infrastructure", []),
            "cdn": tech_profile.get("cdn", []),
            "cms": tech_profile.get("cms", []),
            "tech_tags": tech_profile.get("tech_tags", []),
        }

    @staticmethod
    def _nuclei_normalize_identity_value(value: Any) -> str:
        return re.sub(r"[^a-z0-9._/-]+", "-", str(value or "").lower()).strip("-")

    def _nuclei_group_material(self, finding: Dict) -> Dict:
        """Return a stable logical identity for a Nuclei report group."""
        template = ""
        for key in (
            "nuclei_template", "template", "template_path", "template-path",
            "nuclei_template_id", "template_id", "template-id", "payload",
        ):
            candidate = self._nuclei_normalize_identity_value(finding.get(key))
            if candidate and not candidate.startswith("cluster-"):
                template = candidate
                break
        matcher = self._nuclei_normalize_identity_value(self._nuclei_source_value(
            finding, "nuclei_matcher", "matcher_name", "matcher-name",
        ))
        fallback_name = self._nuclei_normalize_identity_value(
            finding.get("parameter") or str(finding.get("type", "")).replace("NUCLEI:", "")
        )
        return {
            "identity_version": 1,
            "kind": "template",
            "template": template or fallback_name or "unknown",
            "matcher": matcher,
        }

    def _nuclei_group_id(self, finding: Dict) -> str:
        material = self._nuclei_group_material(finding)
        encoded = json.dumps(material, sort_keys=True, separators=(",", ":"))
        return "ng1:" + hashlib.sha256(encoded.encode("utf-8")).hexdigest()

    def _nuclei_state_path(self, scan_id: Optional[int] = None) -> Path:
        state_scan_id = getattr(self, "scan_id", "unknown") if scan_id is None else scan_id
        return self.output_dir / f"reporting_enrichment_state.{state_scan_id}.json"

    def _nuclei_fingerprint(self, finding: Dict) -> str:
        """Fingerprint complete source evidence, excluding generated report text."""
        members = finding.get("nuclei_group_members") or [finding]
        records = []
        for member in members:
            records.append({
                "template": self._nuclei_group_material(member)["template"],
                "matcher": self._nuclei_source_value(member, "nuclei_matcher", "matcher_name", "matcher-name"),
                "name": member.get("parameter", ""),
                "severity": member.get("severity", ""),
                "description": member.get("description", ""),
                "url": member.get("url", ""),
                "extracted_results": member.get("nuclei_extracted_results", ""),
                "request": member.get("nuclei_request") or member.get("request") or "",
                "response": member.get("nuclei_response") or member.get("response") or "",
                "source_fingerprint": member.get("nuclei_source_fingerprint", ""),
            })
        urls = finding.get("affected_urls") or ([finding.get("url")] if finding.get("url") else [])
        material = {
            "version": 1,
            "group_id": finding["nuclei_group_id"],
            "members": sorted(records, key=lambda record: json.dumps(record, sort_keys=True, default=str)),
            "urls": sorted(set(urls)),
        }
        return "ef1:" + hashlib.sha256(
            json.dumps(material, sort_keys=True, separators=(",", ":"), default=str).encode("utf-8")
        ).hexdigest()

    def _load_nuclei_state(self, scan_id: Optional[int] = None) -> Dict:
        expected_scan_id = getattr(self, "scan_id", "unknown") if scan_id is None else scan_id
        path = self._nuclei_state_path(expected_scan_id)
        if not path.is_file():
            return {}
        try:
            state = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            logger.warning(f"[{self.name}] Ignoring corrupt Nuclei narrative state: {exc}")
            return {}
        if (
            not isinstance(state, dict)
            or state.get("schema") != "bugtrace.nuclei-narrative-state"
            or state.get("schema_version") != 1
            or str(state.get("scan_id")) != str(expected_scan_id)
            or not isinstance(state.get("groups"), dict)
        ):
            return {}
        return state

    @staticmethod
    def _async_nuclei_state_file_lock(path: Path):
        """Serialize sidecar read-modify-write operations across API processes."""
        import fcntl
        from contextlib import asynccontextmanager

        @asynccontextmanager
        async def lock():
            lock_path = path.with_name(f".{path.name}.lock")
            handle = lock_path.open("a+b")
            await asyncio.to_thread(fcntl.flock, handle.fileno(), fcntl.LOCK_EX)
            try:
                yield
            finally:
                await asyncio.to_thread(fcntl.flock, handle.fileno(), fcntl.LOCK_UN)
                handle.close()

        return lock()

    async def _persist_nuclei_narratives(self, findings: List[Dict]) -> None:
        """Persist one accepted response as a single sidecar transaction."""
        lock = getattr(self, "_nuclei_state_lock", None)
        if lock is None:
            lock = asyncio.Lock()
            self._nuclei_state_lock = lock
        async with lock:
            async with self._async_nuclei_state_file_lock(self._nuclei_state_path()):
                state = self._load_nuclei_state() or {
                    "schema": "bugtrace.nuclei-narrative-state",
                    "schema_version": 1,
                    "scan_id": getattr(self, "scan_id", "unknown"),
                    "contract_version": self.NUCLEI_NARRATIVE_SCHEMA,
                    "groups": {},
                }
                for finding in findings:
                    state["groups"][finding["nuclei_group_id"]] = {
                        "input_fingerprint": finding["nuclei_input_fingerprint"],
                        "contract_version": self.NUCLEI_NARRATIVE_SCHEMA,
                        "description": finding["description"],
                        "impact": finding["impact"],
                        "remediation": finding["remediation"],
                        "provenance": finding["nuclei_narrative_provenance"],
                        "updated_at": datetime.now().isoformat(),
                    }
                state["updated_at"] = datetime.now().isoformat()
                self._write_nuclei_state(state)

    async def _persist_nuclei_narrative(self, finding: Dict) -> None:
        await self._persist_nuclei_narratives([finding])

    def _prepare_nuclei_fallback(self, finding: Dict) -> None:
        finding.setdefault("description", "Nuclei detected this configuration or exposure from the recorded evidence.")
        finding.setdefault("impact", "The recorded detection should be reviewed in context; it does not alone prove broader compromise.")
        finding.setdefault("remediation", "Review the affected configuration or exposure, apply vendor hardening, and rerun the same Nuclei check.")
        finding.setdefault("nuclei_narrative_provenance", "deterministic")

    def _nuclei_restore_scan_ids(self) -> List[int]:
        """Return this scan plus its direct parent when a resume reuses artifacts."""
        scan_ids = [getattr(self, "scan_id", "unknown")]
        parent_scan_id = getattr(self, "nuclei_parent_scan_id", None)
        if parent_scan_id is None:
            try:
                from bugtrace.schemas.db_models import ScanTable

                with self.db.get_session() as session:
                    scan = session.get(ScanTable, self.scan_id)
                    parent_scan_id = getattr(scan, "resumed_from_id", None) if scan else None
            except Exception:
                parent_scan_id = None
        if parent_scan_id not in (None, "", scan_ids[0]):
            scan_ids.append(parent_scan_id)
        return scan_ids

    def _restore_nuclei_narratives(self, findings: List[Dict]) -> int:
        states = [self._load_nuclei_state(scan_id) for scan_id in self._nuclei_restore_scan_ids()]
        restored = 0
        for finding in findings:
            finding["nuclei_group_id"] = finding.get("nuclei_group_id") or self._nuclei_group_id(finding)
            finding["nuclei_input_fingerprint"] = self._nuclei_fingerprint(finding)
            self._prepare_nuclei_fallback(finding)
            for state in states:
                cached = state.get("groups", {}).get(finding["nuclei_group_id"])
                if not isinstance(cached, dict) or (
                    cached.get("input_fingerprint") != finding["nuclei_input_fingerprint"]
                    or cached.get("contract_version") != self.NUCLEI_NARRATIVE_SCHEMA
                ):
                    continue
                if all(isinstance(cached.get(field), str) and cached[field].strip() for field in ("description", "impact", "remediation")):
                    for field in ("description", "impact", "remediation"):
                        finding[field] = cached[field]
                    finding["nuclei_narrative_provenance"] = "restored"
                    restored += 1
                    break
        return restored

    def _nuclei_batch_prompt(self, findings: List[Dict]) -> str:
        entries = []
        for finding in findings:
            urls = sorted(set(finding.get("affected_urls") or ([finding.get("url")] if finding.get("url") else [])))
            entries.append({
                "id": finding["nuclei_group_id"],
                "type": str(finding.get("type", "")).replace("NUCLEI:", ""),
                "evidence": self._nuclei_prompt_evidence(finding) or "(evidence exceeds safe prompt bound)",
                "affected_urls": urls[:10],
            })
        return f"""You are a senior penetration tester writing grounded client-facing Nuclei report entries.
Analyze ONLY supplied evidence. Do not invent versions, CVEs, payloads, behavior, or exploitability.
Return ONLY this JSON object: {{"schema_version":"{self.NUCLEI_NARRATIVE_SCHEMA}","results":[{{"id":"exact supplied id","description":"...","impact":"...","remediation":"..."}}]}}.
Every requested id must appear exactly once and all three narrative fields must be non-empty.
Requested entries: {json.dumps(entries, ensure_ascii=False)}"""

    def _parse_nuclei_batch_response(self, response: str, expected_ids: set[str]) -> Dict[str, Dict]:
        payload = safe_json_loads(response, fallback=None)
        if not isinstance(payload, dict) or payload.get("schema_version") != self.NUCLEI_NARRATIVE_SCHEMA:
            return {}
        rows = extract_json_list(payload, "results", fallback=None)
        if not isinstance(rows, list):
            return {}
        accepted, duplicate_ids, seen_ids = {}, set(), set()
        for row in rows:
            if not isinstance(row, dict) or row.get("id") not in expected_ids:
                continue
            group_id = row["id"]
            if group_id in seen_ids:
                duplicate_ids.add(group_id)
                continue
            seen_ids.add(group_id)
            narrative = {field: row.get(field) for field in ("description", "impact", "remediation")}
            if all(isinstance(value, str) and value.strip() and len(value) <= self.NUCLEI_NARRATIVE_MAX_FIELD_CHARS for value in narrative.values()):
                accepted[group_id] = narrative
        for group_id in duplicate_ids:
            accepted.pop(group_id, None)
        return accepted

